package config

import (
	"fmt"
	"log"
	"os"

	"gopkg.in/yaml.v3"
)

// Config is the top-level configuration for a MeshDesk node.
type Config struct {
	Node       NodeConfig          `yaml:"node"`
	Mesh       MeshConfig          `yaml:"mesh"`
	Peers      []PeerConfig        `yaml:"peers"`
	P2P        P2pConfig           `yaml:"p2p,omitempty"`
	Monitoring MonitoringConfig    `yaml:"monitoring"`
	WebSSH     WebSSHConfig        `yaml:"webssh"`
	Auth       AuthConfig          `yaml:"auth"`
	Transfer   TransferConfig      `yaml:"transfer"`
	Proxy      ProxyConfig         `yaml:"proxy,omitempty"`
	Reality    RealityServerConfig `yaml:"reality,omitempty"`
	Join       JoinConfig          `yaml:"join,omitempty"`
	Tun        TunConfig           `yaml:"tun,omitempty"`
	ACL        ACLConfig           `yaml:"acl,omitempty"`
	Logging    LoggingConfig       `yaml:"logging,omitempty"`
}

// LoggingConfig controls application-level log output and rotation.
// When LogFile is empty (the default), logs go to stderr as before.
// When LogFile is set, logs are written to that file with automatic
// rotation when the file exceeds LogMaxSize bytes, keeping at most
// LogMaxBackups rotated copies.
type LoggingConfig struct {
	// LogFile is the path to the log file. When empty, logs are
	// written to stderr (the Go standard log default). When set,
	// all log.Printf output is redirected to this file.
	LogFile string `yaml:"log_file,omitempty"`

	// LogMaxSize is the maximum size in bytes of the log file
	// before it is rotated. Default: 10485760 (10 MB).
	// Ignored when LogFile is empty.
	LogMaxSize int64 `yaml:"log_max_size,omitempty"`

	// LogMaxBackups is the maximum number of rotated backup files
	// to retain. Older backups are deleted. Default: 5.
	// Ignored when LogFile is empty.
	LogMaxBackups int `yaml:"log_max_backups,omitempty"`

	// LogMaxAge is the maximum number of days to retain rotated
	// log files based on the timestamp encoded in their name.
	// 0 means no age-based deletion. Default: 0.
	// Ignored when LogFile is empty.
	LogMaxAge int `yaml:"log_max_age,omitempty"`

	// LogCompress determines whether rotated log files are
	// compressed with gzip. Default: false.
	LogCompress bool `yaml:"log_compress,omitempty"`

	// LogLevel controls the verbosity of log output.
	// Supported values: "debug", "info", "warn", "error".
	// Default: "info". When set to "debug", mesh and proxy subsystems
	// emit additional diagnostic output.
	LogLevel string `yaml:"log_level,omitempty"`
}

// DefaultLogMaxSize is the default maximum log file size (10 MB).
const DefaultLogMaxSize int64 = 10 << 20

// DefaultLogMaxBackups is the default number of rotated backups to keep.
const DefaultLogMaxBackups = 5

// JoinConfig holds settings for the auto-join protocol.
// When Enabled is true on a shared node, the node runs a join server
// that accepts join requests from new nodes. New nodes use the Join
// section to configure their join client (server URL + token).
type JoinConfig struct {
	// Enabled controls whether the join server is started on this node.
	// Only meaningful on shared nodes (reality.enabled: true).
	Enabled bool `yaml:"enabled,omitempty"`

	// ListenAddr is the address for the join HTTP server.
	// Default: ":8443". Should be behind TLS in production.
	ListenAddr string `yaml:"listen_addr,omitempty"`

	// Secret is the HMAC key used to sign and validate join tokens.
	// This must be the same on the server and shared out-of-band with
	// joining nodes. If empty, a random secret is generated (but then
	// tokens generated by the server cannot be used by external tools).
	Secret string `yaml:"secret,omitempty"`

	// TLSCertFile is the path to the TLS certificate for the join server.
	// If empty, the join server runs plain HTTP (NOT recommended).
	TLSCertFile string `yaml:"tls_cert_file,omitempty"`

	// TLSKeyFile is the path to the TLS private key for the join server.
	TLSKeyFile string `yaml:"tls_key_file,omitempty"`

	// TokenLifetime is how long generated tokens are valid (seconds).
	// Default: 1800 (30 minutes).
	TokenLifetime int `yaml:"token_lifetime,omitempty"`

	// ServerURL is the join server URL used by the join client.
	// e.g., "https://bootstrap.example.com:8443".
	// Only used on joining nodes.
	ServerURL string `yaml:"server_url,omitempty"`

	// Token is the join token used by the join client.
	// Generated by the server's `meshdesk join-token` command.
	// Only used on joining nodes.
	Token string `yaml:"token,omitempty"`

	// InsecureSkipTLSVerify skips TLS certificate verification on the
	// join client. ONLY for testing — never use in production.
	InsecureSkipTLSVerify bool `yaml:"insecure_skip_tls_verify,omitempty"`
}

// TunConfig holds settings for the TUN virtual network interface.
// When Enabled is true, the node creates a TUN device via /dev/net/tun
// and configures it with the specified subnet and MTU. The TUN device
// provides Layer 3 packet routing for the mesh subnet proxy.
type TunConfig struct {
	// Enabled controls whether the TUN device is created on startup.
	// Default: false. Requires CAP_NET_ADMIN or root privileges.
	Enabled bool `yaml:"enabled,omitempty"`

	// Subnet is the CIDR subnet assigned to the TUN interface (e.g. "10.10.0.0/24").
	// The node's TUN IP is derived from this subnet — it takes the first
	// usable address (network address + 1). Required when Enabled is true.
	Subnet string `yaml:"subnet,omitempty"`

	// MTU is the maximum transmission unit for the TUN interface.
	// Default: 1400. Lower than the typical 1500 to account for
	// encapsulation overhead in the mesh transport layer.
	MTU int `yaml:"mtu,omitempty"`

	// Name is the desired TUN interface name (e.g. "mesh0").
	// If empty, the kernel assigns the next available name (tun0, tun1, ...).
	// Names longer than 15 characters are truncated (IFNAMSIZ limit).
	Name string `yaml:"name,omitempty"`

	// SubnetProxies is a list of local CIDR subnets that this node
	// advertises as reachable through its TUN interface. Other mesh
	// nodes will add kernel routes for these subnets via this node's
	// VirtualIP, allowing them to access hosts on the advertised
	// subnets (e.g. a LAN behind the node).
	//
	// Example:
	//   subnet_proxies:
	//     - 192.168.1.0/24
	//     - 10.0.0.0/8
	SubnetProxies []string `yaml:"subnet_proxies,omitempty"`
}

// ACLAction defines whether an ACL rule allows or denies traffic.
type ACLAction string

const (
	ACLActionAllow ACLAction = "allow"
	ACLActionDeny  ACLAction = "deny"
)

// ACLRule defines a single access control rule for TUN traffic.
// Rules are evaluated in order; the first match wins. If no rule
// matches, the default policy is "allow" (backward-compatible with
// pre-ACL deployments).
//
// All fields support wildcard "*" to match any value. CIDR fields
// support standard CIDR notation (e.g. "10.10.0.0/24") or exact IPs.
type ACLRule struct {
	// Action is "allow" or "deny". Required.
	Action ACLAction `yaml:"action"`

	// SourceCIDR matches the source VirtualIP. "*" matches any.
	// Example: "10.10.0.0/24" matches all IPs in that subnet.
	SourceCIDR string `yaml:"src_cidr,omitempty"`

	// DestCIDR matches the destination IP. "*" matches any.
	// Example: "10.10.0.5/32" matches only that exact IP.
	DestCIDR string `yaml:"dst_cidr,omitempty"`

	// Protocol matches the IP protocol: "tcp", "udp", "icmp", or "*".
	Protocol string `yaml:"protocol,omitempty"`

	// SrcPort matches the source port (TCP/UDP only). 0 = any.
	SrcPort int `yaml:"src_port,omitempty"`

	// DstPort matches the destination port (TCP/UDP only). 0 = any.
	DstPort int `yaml:"dst_port,omitempty"`

	// PeerID matches the sending peer's Ed25519 public key (hex).
	// "*" or empty matches any peer. A specific key restricts the
	// rule to traffic from that peer only.
	PeerID string `yaml:"peer_id,omitempty"`

	// Description is a human-readable comment for the rule.
	Description string `yaml:"description,omitempty"`
}

// ACLConfig holds TUN access control list configuration.
type ACLConfig struct {
	// Enabled controls whether ACL checking is active. When false
	// (default), all traffic is allowed (backward-compatible).
	Enabled bool `yaml:"enabled,omitempty"`

	// DefaultPolicy is the action taken when no rule matches.
	// "allow" (default) or "deny".
	DefaultPolicy ACLAction `yaml:"default_policy,omitempty"`

	// Rules is the ordered list of ACL rules. First match wins.
	Rules []ACLRule `yaml:"rules,omitempty"`
}

// DefaultTunMTU is the default MTU for TUN interfaces.
// Set below 1500 to avoid fragmentation when packets traverse the
// mesh transport (Reality TLS + smux + AES-256-GCM overhead).
const DefaultTunMTU = 1400

// DefaultMeshPort is the default mesh listen port (both TCP mux and
// UDP gossip) used when config leaves Mesh.Port unset.
// It is NOT hardcoded in the transport/holepunch layers — those read
// cfg.Mesh.Port. This constant exists only so defaults, CLI tools and
// web handlers reference one source of truth instead of magic numbers.
const DefaultMeshPort = 52888

// ProxyConfig holds settings for the anonymous proxy subsystem
// (multi-path dispersed transport). See docs/PROXY_DESIGN.md.
type ProxyConfig struct {
	// Circuit holds circuit lifecycle parameters.
	Circuit CircuitLifecycleConfig `yaml:"circuit,omitempty"`

	// ChunkerStrategy selects the chunking strategy: "fixed-16k"
	// or "bounded-4k-64k". Default: "bounded-4k-64k".
	ChunkerStrategy string `yaml:"chunker_strategy,omitempty"`

	// DebugFixedChunks forces uniform 16KB chunks for deterministic
	// testing. MUST be false in production.
	DebugFixedChunks bool `yaml:"debug_fixed_chunks,omitempty"`

	// Paths holds manually configured relay paths (Phase 1).
	// Each path is a list of relay node IDs (hex public keys).
	// When PathSelection.Mode is "auto", this is ignored.
	Paths [][]string `yaml:"paths,omitempty"`

	// PathSelection holds dynamic path selection configuration (Phase 2).
	// When enabled, the entry node automatically probes and selects
	// two disjoint paths based on RTT measurements.
	PathSelection PathSelectionConfig `yaml:"path_selection,omitempty"`

	// ExitAddr is the mesh address (mesh_ip:port) of the exit node.
	// Required on entry nodes — the entry node connects to this
	// address to set up circuits and dispatch chunks.
	// Example: "10.10.0.5:8388".
	ExitAddr string `yaml:"exit_addr,omitempty"`

	// Relay holds relay-node-specific configuration.
	// Only needed on nodes that serve as relay nodes.
	Relay RelayNodeConfig `yaml:"relay,omitempty"`

	// Exit holds exit-node-specific configuration.
	// Only needed on nodes that serve as exit nodes.
	Exit ExitConfig `yaml:"exit,omitempty"`

	// SOCKS5 holds SOCKS5 proxy exit configuration.
	// Only needed on nodes that serve as SOCKS5 proxy exits for mesh peers.
	SOCKS5 SOCKS5YAMLConfig `yaml:"socks5,omitempty"`
}

// PathSelectionConfig holds settings for dynamic path selection
// (PROXY_DESIGN.md §1.5, Phase 2).
type PathSelectionConfig struct {
	// Mode selects the path selection mode:
	//   "manual"  — use paths from ProxyConfig.Paths (Phase 1)
	//   "auto"    — probe and select best paths (Phase 2)
	// Default: "manual".
	Mode string `yaml:"mode,omitempty"`

	// Strategy selects the path ranking algorithm used when Mode is
	// "auto". Supported values:
	//   "latency"     — pick the two lowest-RTT disjoint paths (default)
	//   "random"      — random selection from healthy candidates
	//   "round-robin" — cycle through available paths to distribute load
	// Default: "latency".
	Strategy string `yaml:"strategy,omitempty"`

	// MaxRelaysPerPath is the maximum number of relay hops per path.
	// Default: 2. Higher = more anonymity, more latency.
	MaxRelaysPerPath int `yaml:"max_relays_per_path,omitempty"`

	// ProbeTimeoutSec is the timeout for each relay probe (seconds).
	// Default: 3.
	ProbeTimeoutSec int `yaml:"probe_timeout_sec,omitempty"`

	// ProbeConcurrency limits concurrent probes.
	// Default: 8.
	ProbeConcurrency int `yaml:"probe_concurrency,omitempty"`

	// MaxCandidates is the maximum number of relays to probe.
	// Implements O(K) scaling per PROXY_DESIGN.md §1.5.
	// Default: 10.
	MaxCandidates int `yaml:"max_candidates,omitempty"`

	// ProbeCacheTTLSec is how long cached probe results are valid.
	// Default: 30.
	ProbeCacheTTLSec int `yaml:"probe_cache_ttl_sec,omitempty"`

	// ExitLatencyMatrix holds exit→region RTT data for exit selection.
	// Map key: exit node ID → map[region]RTT in milliseconds.
	// Used by SelectExit to pick the optimal exit for a target.
	ExitLatencyMatrix map[string]map[string]int `yaml:"exit_latency_matrix,omitempty"`
}

// RelayNodeConfig holds settings for a relay node in the anonymous
// proxy system. Relay nodes blindly forward AEAD-encrypted ciphertext
// chunks — they have no decryption key for the payload and only process
// the forwarding header to determine the next hop.
//
// See PROXY_DESIGN.md §1.7 (Identity Trust Boundary) and §1.9
// (Forwarding Header Obfuscation).
type RelayNodeConfig struct {
	// Enabled indicates whether this node is intentionally configured
	// as a relay node. When false, the relay module should not be
	// instantiated and the node should NOT be treated as a relay in
	// topology role derivation.
	//
	// This field exists because Default() pre-populates relay tuning
	// parameters (MaxCircuits=1024, etc.) so that relay-enabled nodes
	// have sane defaults without requiring every field. Without an
	// explicit Enabled flag, checking MaxCircuits > 0 would incorrectly
	// classify every Default()-derived node as a relay.
	Enabled bool `yaml:"enabled,omitempty"`

	// JitterMinMs is the minimum forwarding delay per chunk in
	// milliseconds. Default: 5 (per PROXY_DESIGN.md §1.9).
	JitterMinMs int `yaml:"jitter_min_ms,omitempty"`

	// JitterMaxMs is the maximum forwarding delay per chunk in
	// milliseconds. Default: 50 (per PROXY_DESIGN.md §1.9).
	JitterMaxMs int `yaml:"jitter_max_ms,omitempty"`

	// DisableJitter, when true, skips the random delay. MUST be
	// false in production — timing side-channels would be exploitable.
	DisableJitter bool `yaml:"disable_jitter,omitempty"`

	// MaxCircuits limits the number of concurrent circuits a relay
	// will accept. Default: 1024.
	MaxCircuits int `yaml:"max_circuits,omitempty"`

	// MaxQueueDepth is the maximum number of pending chunks per
	// circuit before backpressure is applied. Default: 256.
	MaxQueueDepth int `yaml:"max_queue_depth,omitempty"`
}

// CircuitLifecycleConfig holds circuit lifecycle parameters.
// These map to the CircuitConfig in internal/proxy/protocol.go.
type CircuitLifecycleConfig struct {
	// IdleTimeout is how long a circuit stays active without data
	// before automatic teardown (seconds). Default: 300 (5 min).
	IdleTimeout int `yaml:"idle_timeout,omitempty"`

	// KeepaliveInterval is how often the entry sends keepalive pings
	// (seconds). Default: 30.
	KeepaliveInterval int `yaml:"keepalive_interval,omitempty"`

	// NACKTimeout is how long the exit waits for a missing chunk
	// before sending a NACK (seconds). Default: 5.
	NACKTimeout int `yaml:"nack_timeout,omitempty"`

	// OrphanTimeout is how long the exit keeps an incomplete reassembly
	// buffer (seconds). Default: 30.
	OrphanTimeout int `yaml:"orphan_timeout,omitempty"`

	// MaxReassemblyWindow is the hard limit on reassembly window size.
	// Default: 256.
	MaxReassemblyWindow int `yaml:"max_reassembly_window,omitempty"`
}

// ExitConfig holds exit-node-specific configuration.
type ExitConfig struct {
	// AllowedPorts is the list of destination ports the exit will
	// connect to. Default: [80, 443]. Operators can expand this
	// at their own legal risk.
	AllowedPorts []int `yaml:"allowed_ports,omitempty"`

	// AllowAllPorts removes the port restriction entirely.
	// WARNING: full legal exposure. Not recommended.
	AllowAllPorts bool `yaml:"allow_all_ports,omitempty"`

	// DestinationFilter is a list of CIDR prefixes or FQDN patterns
	// that the exit is allowed to connect to. When non-empty, the
	// exit refuses connections to destinations that don't match at
	// least one entry. Empty (default) allows all destinations
	// subject to AllowedPorts/AllowAllPorts.
	// Examples: "10.0.0.0/8", "*.example.com", "203.0.113.0/24".
	DestinationFilter []string `yaml:"destination_filter,omitempty"`

	// AuditLogDir is the directory for exit audit logs.
	// Logs record circuit_id → dest_ip:port → timestamp (no payload).
	AuditLogDir string `yaml:"audit_log_dir,omitempty"`

	// AuditRetentionDays is how long to keep audit logs. Default: 7.
	AuditRetentionDays int `yaml:"audit_retention_days,omitempty"`
}

// SOCKS5YAMLConfig holds SOCKS5 proxy exit configuration.
// When Enabled is true, the node registers a SOCKS5 handler on virtual
// port 0x5350, allowing mesh peers to route SOCKS5 CONNECT requests
// through this node to reach arbitrary internet destinations.
type SOCKS5YAMLConfig struct {
	// Enabled controls whether the SOCKS5 handler is started.
	Enabled bool `yaml:"enabled,omitempty"`

	// AllowedPorts restricts which destination ports the handler will
	// connect to. Default: [80, 443]. Use AllowAllPorts to remove the
	// restriction.
	AllowedPorts []int `yaml:"allowed_ports,omitempty"`

	// AllowAllPorts removes the port restriction entirely.
	// WARNING: full legal exposure. Not recommended.
	AllowAllPorts bool `yaml:"allow_all_ports,omitempty"`

	// DestinationFilter is a list of CIDR prefixes that the handler is
	// allowed to connect to. When non-empty, the handler refuses
	// connections to destinations that don't match at least one entry.
	// Empty (default) allows all destinations subject to AllowedPorts.
	DestinationFilter []string `yaml:"destination_filter,omitempty"`

	// DialTimeoutSec is the timeout for dialing target addresses (seconds).
	// Default: 30.
	DialTimeoutSec int `yaml:"dial_timeout_sec,omitempty"`

	// IdleTimeoutSec is the idle timeout for established connections
	// (seconds). Connections with no data flow for this duration are
	// closed. Default: 300 (5 minutes).
	IdleTimeoutSec int `yaml:"idle_timeout_sec,omitempty"`

	// MaxConnections limits concurrent SOCKS5 connections. Default: 256.
	MaxConnections int `yaml:"max_connections,omitempty"`

	// AllowedPeers restricts which mesh peers can connect to this
	// SOCKS5 proxy by identity. Each entry is a mesh identity hex
	// string (64 hex chars for Ed25519 public key). Empty means all
	// mesh peers are allowed.
	AllowedPeers []string `yaml:"allowed_peers,omitempty"`

	// RequireMeshPeer rejects SOCKS5 connections from non-mesh sources
	// (e.g. phone clients that connect via Reality TLS without a mesh
	// identity). Default: false.
	RequireMeshPeer bool `yaml:"require_mesh_peer,omitempty"`

	// EntryListen enables the local SOCKS5 entry listener (the
	// --socks5-listen equivalent) when non-empty. Empty = disabled.
	// Managed from the Dashboard Proxy page; the CLI flag still wins.
	EntryListen string `yaml:"entry_listen,omitempty"`

	// EntryUsername/EntryPassword enable RFC 1929 username/password
	// authentication on the entry listener when both are non-empty.
	// A listener on a non-loopback address without credentials is
	// refused (no bare exposed socks5 proxies).
	EntryUsername string `yaml:"entry_username,omitempty"`
	EntryPassword string `yaml:"entry_password,omitempty"`

	// ExitNode pins this entry's traffic to a single fixed exit node
	// (peer identity hex). Mutually exclusive with ExitNodes.
	ExitNode string `yaml:"exit_node,omitempty"`

	// ExitNodes is an ordered list of exit node identities for this
	// entry. The exit with the lowest live RTT is selected per
	// connection; failures fall back to the next in the list.
	ExitNodes []string `yaml:"exit_nodes,omitempty"`
}

// TransferConfig holds file transfer settings.
type TransferConfig struct {
	// MaxFileSize is the maximum size in bytes for a single incoming file
	// transfer. A value of 0 means no limit (not recommended for production).
	// Defaults to 1 GB (1 << 30) when unset.
	MaxFileSize int64 `yaml:"max_file_size"`

	// UploadDir is the directory where incoming file transfers are written.
	// Defaults to /tmp/meshdesk-uploads/ when empty.
	UploadDir string `yaml:"upload_dir"`
}

// DefaultIdentityFile is the default path for the PEM-encoded identity file.
// The identity file contains the Ed25519 private key in PKCS#8 PEM format
// (RFC 8410) with 0600 permissions. Only the public key fingerprint is
// stored in config.yaml for reference.
const DefaultIdentityFile = "/etc/meshdesk/identity.pem"

// NodeConfig holds local node identity settings.
type NodeConfig struct {
	// Identity is the deprecated hex-encoded Ed25519 private key.
	// Kept for backward compatibility migration only — new configs
	// store the private key in IdentityFile (PEM format) and only
	// a fingerprint (public key hex) here.
	// On load, if Identity is set and IdentityFile is not, the key
	// is migrated to the PEM file and this field is cleared.
	// This field is never written to YAML by new code (omitempty + cleared).
	Identity string `yaml:"identity,omitempty"` // DEPRECATED: hex private key; migrated to IdentityFile

	// IdentityFile is the path to the PEM file containing the Ed25519
	// private key. Default: /etc/meshdesk/identity.pem (0600 perms).
	// The file is created automatically on first run if it doesn't exist.
	IdentityFile string `yaml:"identity_file,omitempty"`

	// Fingerprint is the hex-encoded Ed25519 public key, stored in
	// config.yaml for reference only. It is NOT used for authentication
	// — the actual key material is read from IdentityFile.
	Fingerprint string `yaml:"fingerprint,omitempty"`

	Hostname string `yaml:"hostname"` // auto-detected if empty
	WebAddr  string `yaml:"web"`      // e.g. ":8080"; empty = agent-only mode

	// Position holds an optional manual 3D display position for topology
	// visualization. When nil, positions are auto-derived from the node's
	// public key (see topology.DerivePosition). This is display-only
	// metadata and does not affect routing or proxy behavior.
	Position *PositionConfig `yaml:"position,omitempty"`
}

// PositionConfig holds a manual 3D display position for the topology
// visualization. Coordinates are in arbitrary screen-space units.
type PositionConfig struct {
	X float64 `yaml:"x"`
	Y float64 `yaml:"y"`
	Z float64 `yaml:"z"`
}

// MeshConfig holds mesh-level settings.
type MeshConfig struct {
	Port int `yaml:"port"` // mesh/Reality listen port

	// Zone is this node's zone tag (free-form string, e.g. "cn", "us",
	// "uk"). Peers with the SAME zone value use UDP P2P (multipath +
	// hole-punching); peers with a DIFFERENT zone (or unknown) use
	// Reality TLS only. Empty = unknown (conservative: Reality for all).
	Zone string `yaml:"zone,omitempty"`

	// --- TUN virtual network interface ---

	// TunEnabled controls whether the TUN device is created on startup.
	// When true, the node creates a TUN interface, allocates a VirtualIP
	// via IPAM, and syncs kernel routes for peer VirtualIPs.
	// Default: false. Requires CAP_NET_ADMIN or root.
	TunEnabled bool `yaml:"tun_enabled,omitempty"`

	// MeshCIDR is the CIDR subnet for the TUN interface (e.g. "10.144.144.0/24").
	// The node's VirtualIP is allocated from this subnet by the IPAM
	// deterministic allocator. Required when TunEnabled is true.
	MeshCIDR string `yaml:"mesh_cidr,omitempty"`

	// SubnetProxy is a list of local CIDR subnets that this node
	// advertises as reachable through its TUN interface (e.g. a LAN
	// behind it). Other nodes add kernel routes for these subnets
	// via this node's VirtualIP.
	SubnetProxy []string `yaml:"subnet_proxy,omitempty"`

	// TunName is the desired TUN interface name (e.g. "mesh0").
	// If empty, defaults to "mesh0".
	TunName string `yaml:"tun_name,omitempty"`

	// TunMTU is the MTU for the TUN interface. Default: 1400.
	TunMTU int `yaml:"tun_mtu,omitempty"`

	// StaticVirtualIP forces a specific VirtualIP instead of using IPAM
	// allocation. When set, the node uses this IP regardless of peer
	// state. Use only when IPAM cannot converge (e.g., single-node
	// testing, NAT-separated nodes with no relay).
	// Format: "10.100.0.2". The IP must be within mesh_cidr.
	StaticVirtualIP string `yaml:"static_virtual_ip,omitempty"`

	// --- Mesh DNS server ---

	// DNSEnabled controls whether the built-in lightweight DNS server
	// is started. When true, the node listens on DNSPort (UDP) and
	// resolves <hostname>.mesh queries to the corresponding peer's
	// VirtualIP using gossip-synchronized node metadata.
	// Default: false. Only meaningful when both TUN and P2P gossip
	// are enabled (DNS resolution requires VirtualIPs from gossip).
	DNSEnabled bool `yaml:"dns_enabled,omitempty"`

	// DNSPort is the UDP port for the built-in DNS server.
	// Default: 5353. Set to 53 to act as the mesh-wide resolver
	// (requires CAP_NET_BIND_SERVICE or root).
	DNSPort int `yaml:"dns_port,omitempty"`

	// FileTransferPaths restricts the cluster FileServer (0x1F4) to
	// these directory prefixes. Empty = serve any path (peer
	// authorization still applies via ACL).
	FileTransferPaths []string `yaml:"file_transfer_paths,omitempty"`
}

// P2pConfig holds settings for the P2P dynamic networking layer
// (gossip discovery, NAT traversal, dynamic join).
// When Enabled is false, the node uses static peers only (backward compat).
type P2pConfig struct {
	// Enabled controls whether dynamic P2P networking is active.
	Enabled bool `yaml:"enabled,omitempty"`

	// Seeds is the list of known mesh endpoints used to
	// bootstrap the mesh cluster.
	Seeds []string `yaml:"seeds,omitempty"`

	// RelayMode controls how relay fallback is handled:
	//   "auto"     — automatically select relay peers (default)
	//   "manual"   — use only manually configured relay peers
	//   "disabled" — no relay fallback (direct-only)
	RelayMode string `yaml:"relay_mode,omitempty"`

	// MaxRelayHops is the maximum number of relay hops for relayed connections.
	MaxRelayHops int `yaml:"max_relay_hops,omitempty"`

	// AdvertiseEndpoints is a list of explicit mesh endpoints (host:port)
	// that this node advertises to peers via META. When set, they override
	// the auto-detected local IP. Use this when the node is behind NAT and you
	// know the public IP:port mapping, or when auto-detection would pick the
	// wrong interface (e.g., Docker, multi-homed hosts, dual-stack IPv4/IPv6).
	AdvertiseEndpoints []string `yaml:"advertise_endpoints,omitempty"`

	// AdvertiseEndpoint is a legacy field for backward compatibility.
	// If set, it is treated as a single-element AdvertiseEndpoints list
	// during config loading. Deprecated: use advertise_endpoints instead.
	AdvertiseEndpoint string `yaml:"advertise_endpoint,omitempty"`
}

// PeerConfig describes a single mesh peer.
type PeerConfig struct {
	PublicKey    string   `yaml:"public_key"`
	Endpoint     string   `yaml:"endpoint"`     // host:port; empty for roaming
	AllowedIPs   []string `yaml:"allowed_ips"`  // v2: kept for routing table compatibility
	Capabilities []string `yaml:"capabilities"` // what this peer can do on us

	// Zone is the peer's zone tag (free-form, e.g. "cn", "us"). The
	// connection policy: SAME zone as ours → UDP P2P; different or
	// unknown (empty) → Reality TLS only. This is the primary
	// transport-selection signal.
	Zone string `yaml:"zone,omitempty"`

	// Reality holds per-peer Reality TLS transport configuration.
	// In v2, this is the only transport mode. See docs/MESHDESK_V2_DESIGN.md.
	Reality *RealityPeerConfig `yaml:"reality,omitempty"`

	// ServiceManage holds the list of service names this peer is allowed to
	// manage (start/stop/restart). Only meaningful when "service_manage"
	// appears in Capabilities. If empty with service_manage present, the
	// peer can manage all services (not recommended).
	ServiceManage []string `yaml:"service_manage,omitempty"`

	// FileTransferPaths restricts file_transfer capability to specific
	// directory prefixes. If empty with file_transfer present, no path
	// restriction is enforced (peer can access any path).
	FileTransferPaths []string `yaml:"file_transfer_paths,omitempty"`

	// MonitorScopes restricts monitor_read/monitor_write to specific
	// metric categories. If empty, all metrics are accessible.
	MonitorScopes []string `yaml:"monitor_scopes,omitempty"`
}

// RealityPeerConfig holds per-peer Reality TLS client-side configuration.
// Used when a peer's obfuscation mode is "reality".
type RealityPeerConfig struct {
	// ServerName is the SNI hostname sent in the TLS ClientHello.
	// e.g. "www.apple.com". Must match one of the server's accepted
	// server_names.
	ServerName string `yaml:"server_name"`

	// PublicKey is the server's X25519 public key (hex-encoded).
	// Used client-side to derive the REALITY auth key via ECDH.
	PublicKey string `yaml:"public_key"`

	// ShortID is the per-client short ID for REALITY authentication
	// (hex-encoded, up to 8 bytes). Must be in the server's short_ids list.
	ShortID string `yaml:"short_id"`

	// TLSFingerprint is the browser ClientHello to mimic.
	// Default: "chrome". Supported: chrome, firefox, safari, edge, ios, android.
	TLSFingerprint string `yaml:"tls_fingerprint,omitempty"`
}

// RealityServerConfig holds server-side Reality TLS configuration.
// Only needed on nodes that serve as relay/shared nodes accepting
// Reality TLS connections.
type RealityServerConfig struct {
	// Enabled controls whether the Reality TLS listener is started.
	Enabled bool `yaml:"enabled,omitempty"`

	// ListenAddr is the address to listen on. Default: ":443".
	ListenAddr string `yaml:"listen_addr,omitempty"`

	// ListenPort overrides the port in ListenAddr. Default: 443.
	ListenPort int `yaml:"listen_port,omitempty"`

	// Dest is the camouflage target — the real website to proxy
	// non-mesh traffic to (failing REALITY auth).
	// e.g. "www.apple.com:443"
	Dest string `yaml:"dest"`

	// ServerNames is the list of accepted SNI values.
	// Only connections presenting one of these SNIs pass auth.
	ServerNames []string `yaml:"server_names,omitempty"`

	// PrivateKey is the X25519 private key (hex-encoded) used
	// server-side for REALITY ECDH authentication.
	PrivateKey string `yaml:"private_key"`

	// ShortIDs is the list of accepted short IDs (hex-encoded).
	ShortIDs []string `yaml:"short_ids,omitempty"`
}

// MonitoringConfig holds monitoring/push settings.
type MonitoringConfig struct {
	Collectors []string `yaml:"collectors"` // peer IDs of collector nodes
	Interval   int      `yaml:"interval"`   // push interval in seconds
	Port       int      `yaml:"port"`       // mesh-internal port for metric pushes (default 4191)
}

// AuthConfig holds web UI auth settings.
type AuthConfig struct {
	WebUsers []WebUser `yaml:"web_users"`

	// TOTPIssuer is the issuer name embedded in otpauth:// URIs shown
	// in QR codes during 2FA enrollment. Default: "MeshDesk".
	TOTPIssuer string `yaml:"totp_issuer,omitempty"`

	// Require2FA, when true, mandates that all web dashboard users
	// complete TOTP enrollment before accessing any authenticated
	// endpoint. When false (default), 2FA enrollment is optional.
	Require2FA bool `yaml:"require_2fa,omitempty"`

	// TOTPWindow is the ±skew tolerance in time steps (default 1).
	// Each step is 30 seconds, so a value of 1 accepts codes from
	// the previous, current, and next 30-second windows.
	TOTPWindow int `yaml:"totp_window,omitempty"`

	// TOTPStoreDir is the directory for persistent TOTP encrypted state
	// storage. When set, TOTP enrollment state is encrypted and persisted
	// to <TOTPStoreDir>/users/<username>.enc, surviving process restarts.
	// When empty (default), TOTP state is in-memory only and lost on restart.
	// Production deployments should set this to /var/lib/meshdesk/totp.
	TOTPStoreDir string `yaml:"totp_store_dir,omitempty"`

	// StepUpTimeout is the lifetime of a step-up auth token in seconds
	// (default 300 = 5 minutes). After this period, sensitive operations
	// require re-authentication.
	StepUpTimeout int `yaml:"step_up_timeout,omitempty"`

	// AlertWebhookURL is an optional webhook endpoint for external
	// security alert notifications. When empty, alerts are only stored
	// in-memory and surfaced in the web UI.
	AlertWebhookURL string `yaml:"alert_webhook_url,omitempty"`

	// legacyTOTPSecret captures a deprecated totp_secret value found in
	// config.yaml during Load(). It is NOT serialized (no yaml tag) and
	// is used only for one-time migration to the node-local master secret.
	// Access via LegacyTOTPSecret() method.
	legacyTOTPSecret string `yaml:"-"`
}

// WebSSHConfig holds settings for the WebSSH bridge.
type WebSSHConfig struct {
	// Port is the mesh-internal port for the SSH server on the target node.
	// Default: 2222.
	Port int `yaml:"port"`

	// HostKey is the SSH host private key (PEM-encoded). If empty, an
	// Ed25519 key is auto-generated on startup.
	HostKey string `yaml:"host_key"`

	// Shell is the default shell to launch. If empty, auto-detected via
	// /etc/passwd, falling back to /bin/bash then /bin/sh.
	Shell string `yaml:"shell"`

	// DialTimeout is how long the web server node waits when dialing
	// the target node's SSH server over the mesh VPN (seconds, default 10).
	DialTimeout int `yaml:"dial_timeout"`

	// ReadDeadline is the WebSocket read deadline for idle sessions
	// (seconds, default 300 = 5 minutes).
	ReadDeadline int `yaml:"read_deadline"`

	// WriteDeadline is the WebSocket write deadline (seconds, default 10).
	WriteDeadline int `yaml:"write_deadline"`

	// MaxSessions limits concurrent terminal sessions per node (default 256).
	MaxSessions int `yaml:"max_sessions"`
}

// WebUser is a web UI login account.
type WebUser struct {
	Username     string `yaml:"username"`
	PasswordHash string `yaml:"password_hash"`
}

// DefaultMaxFileSize is the default limit for incoming file transfers (1 GB).
const DefaultMaxFileSize int64 = 1 << 30

// DefaultUploadDir is the default directory for incoming file transfers.
const DefaultUploadDir = "/tmp/meshdesk-uploads/"

// DefaultTOTPStoreDir is the default directory for persistent TOTP
// encrypted state storage.
const DefaultTOTPStoreDir = "/var/lib/meshdesk/totp"

// Default returns a config with sensible defaults.
func Default() *Config {
	return &Config{
		Node: NodeConfig{
			WebAddr:      "",
			IdentityFile: DefaultIdentityFile,
		},
		Mesh: MeshConfig{
			Port:       DefaultMeshPort,
			TunMTU:     DefaultTunMTU,
			TunEnabled: true,
			TunName:    "mesh0",
			MeshCIDR:   "10.100.0.0/24",
			DNSPort:    5353,
			DNSEnabled: true,
		},
		Monitoring: MonitoringConfig{
			Interval: 15,
		},
		WebSSH: WebSSHConfig{
			Port:          2222,
			DialTimeout:   10,
			ReadDeadline:  300,
			WriteDeadline: 10,
			MaxSessions:   256,
		},
		Transfer: TransferConfig{
			MaxFileSize: DefaultMaxFileSize,
			UploadDir:   DefaultUploadDir,
		},
		Auth: AuthConfig{
			TOTPIssuer:    "MeshDesk",
			TOTPWindow:    1,
			StepUpTimeout: 300,
		},
		Proxy: ProxyConfig{
			ChunkerStrategy: "bounded-4k-64k",
			Circuit: CircuitLifecycleConfig{
				IdleTimeout:         300,
				KeepaliveInterval:   30,
				NACKTimeout:         5,
				OrphanTimeout:       30,
				MaxReassemblyWindow: 256,
			},
			Exit: ExitConfig{
				AllowedPorts:       []int{80, 443},
				AuditRetentionDays: 7,
			},
			Relay: RelayNodeConfig{
				JitterMinMs:   5,
				JitterMaxMs:   50,
				MaxCircuits:   1024,
				MaxQueueDepth: 256,
			},
			PathSelection: PathSelectionConfig{
				Mode:     "manual",
				Strategy: "latency",
			},
		},
		P2P: P2pConfig{
			Enabled:      false, // memberlist deprecated — META replaces discovery
			RelayMode:    "auto",
			MaxRelayHops: 2,
		},
		ACL: ACLConfig{
			DefaultPolicy: ACLActionAllow,
		},
	}
}

// Load reads and parses a YAML config from path.
//
// The YAML decoder is configured with KnownFields(false) (the yaml.v3
// default), so unknown top-level sections — e.g. a leftover xray: block
// from a pre-refactor config — are silently ignored rather than causing
// a hard-fail. A warning is logged for each unrecognised top-level key
// so operators can spot stale sections during cleanup.
func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read config: %w", err)
	}
	cfg := Default()
	if err := yaml.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}

	// Warn about unrecognised top-level keys (e.g. leftover xray: section).
	warnUnknownTopLevelKeys(data)
	// Detect deprecated totp_secret in config.yaml (removed field).
	// The TOTP encryption key is now node-local at /var/lib/meshdesk/totp/master.key.
	if legacySecret := extractLegacyTOTPSecret(data); legacySecret != "" {
		cfg.Auth.legacyTOTPSecret = legacySecret
		log.Printf("[WARNING] config.yaml contains deprecated field 'totp_secret' — " +
			"TOTP encryption now uses node-local /var/lib/meshdesk/totp/master.key. " +
			"The config field is ignored and should be removed.")
	}
	if cfg.Mesh.Port == 0 {
		cfg.Mesh.Port = DefaultMeshPort
	}
	// TUN config defaults for MeshConfig fields.
	if cfg.Mesh.TunMTU == 0 {
		cfg.Mesh.TunMTU = DefaultTunMTU
	}
	if cfg.Mesh.TunName == "" && cfg.Mesh.TunEnabled {
		cfg.Mesh.TunName = "mesh0"
	}
	// DNS config defaults.
	if cfg.Mesh.DNSPort == 0 && cfg.Mesh.DNSEnabled {
		cfg.Mesh.DNSPort = 5353
	}
	// Backward compatibility: if the top-level tun: section has fields
	// set and the mesh.* fields don't, migrate from tun: to mesh.
	if cfg.Tun.Enabled && !cfg.Mesh.TunEnabled {
		cfg.Mesh.TunEnabled = true
	}
	if cfg.Tun.Subnet != "" && cfg.Mesh.MeshCIDR == "" {
		cfg.Mesh.MeshCIDR = cfg.Tun.Subnet
	}
	if cfg.Tun.Name != "" && cfg.Mesh.TunName == "" {
		cfg.Mesh.TunName = cfg.Tun.Name
	}
	if cfg.Tun.MTU != 0 && cfg.Mesh.TunMTU == 0 {
		cfg.Mesh.TunMTU = cfg.Tun.MTU
	}
	if len(cfg.Tun.SubnetProxies) > 0 && len(cfg.Mesh.SubnetProxy) == 0 {
		cfg.Mesh.SubnetProxy = cfg.Tun.SubnetProxies
	}
	// P2P config: memberlist retired — defaults are minimal.
	// Peer reality defaults: server_name and short_id have standard
	// values shared across the mesh — users only write public_key.
	for i := range cfg.Peers {
		if cfg.Peers[i].Reality == nil {
			cfg.Peers[i].Reality = &RealityPeerConfig{}
		}
		if cfg.Peers[i].Reality.ServerName == "" {
			cfg.Peers[i].Reality.ServerName = "www.microsoft.com"
		}
		if cfg.Peers[i].Reality.ShortID == "" {
			cfg.Peers[i].Reality.ShortID = "0123456789abcdef"
		}
		if cfg.Peers[i].Reality.TLSFingerprint == "" {
			cfg.Peers[i].Reality.TLSFingerprint = "chrome"
		}
	}
	// TUN defaults: enabled by default with standard mesh CIDR.
	if cfg.Mesh.TunName == "" {
		cfg.Mesh.TunName = "mesh0"
	}
	if cfg.Mesh.MeshCIDR == "" {
		cfg.Mesh.MeshCIDR = "10.100.0.0/24"
	}
	if cfg.P2P.RelayMode == "" && cfg.P2P.Enabled {
		cfg.P2P.RelayMode = "auto"
	}
	if cfg.P2P.MaxRelayHops == 0 && cfg.P2P.Enabled {
		cfg.P2P.MaxRelayHops = 2
	}
	// Backward compatibility: if the legacy advertise_endpoint field is set
	// and advertise_endpoints is not, migrate the single endpoint to the list.
	if cfg.P2P.AdvertiseEndpoint != "" && len(cfg.P2P.AdvertiseEndpoints) == 0 {
		cfg.P2P.AdvertiseEndpoints = []string{cfg.P2P.AdvertiseEndpoint}
	}
	if cfg.Monitoring.Interval == 0 {
		cfg.Monitoring.Interval = 15
	}
	if cfg.Monitoring.Port == 0 {
		cfg.Monitoring.Port = 4191
	}
	if cfg.WebSSH.Port == 0 {
		cfg.WebSSH.Port = 2222
	}
	if cfg.WebSSH.DialTimeout == 0 {
		cfg.WebSSH.DialTimeout = 10
	}
	if cfg.WebSSH.ReadDeadline == 0 {
		cfg.WebSSH.ReadDeadline = 300
	}
	if cfg.WebSSH.WriteDeadline == 0 {
		cfg.WebSSH.WriteDeadline = 10
	}
	if cfg.WebSSH.MaxSessions == 0 {
		cfg.WebSSH.MaxSessions = 256
	}
	if cfg.Transfer.MaxFileSize == 0 {
		cfg.Transfer.MaxFileSize = DefaultMaxFileSize
	}
	if cfg.Transfer.UploadDir == "" {
		cfg.Transfer.UploadDir = DefaultUploadDir
	}
	// Auth config defaults.
	if cfg.Auth.TOTPIssuer == "" {
		cfg.Auth.TOTPIssuer = "MeshDesk"
	}
	if cfg.Auth.TOTPWindow == 0 {
		cfg.Auth.TOTPWindow = 1
	}
	if cfg.Auth.StepUpTimeout == 0 {
		cfg.Auth.StepUpTimeout = 300
	}
	// Enable persistent TOTP storage by default in production (when
	// loaded from config file). Tests use config.Default() which
	// leaves this empty for in-memory mode.
	if cfg.Auth.TOTPStoreDir == "" {
		cfg.Auth.TOTPStoreDir = DefaultTOTPStoreDir
	}
	// Proxy config defaults.
	if cfg.Proxy.ChunkerStrategy == "" {
		cfg.Proxy.ChunkerStrategy = "bounded-4k-64k"
	}
	if cfg.Proxy.Circuit.IdleTimeout == 0 {
		cfg.Proxy.Circuit.IdleTimeout = 300
	}
	if cfg.Proxy.Circuit.KeepaliveInterval == 0 {
		cfg.Proxy.Circuit.KeepaliveInterval = 30
	}
	if cfg.Proxy.Circuit.NACKTimeout == 0 {
		cfg.Proxy.Circuit.NACKTimeout = 5
	}
	if cfg.Proxy.Circuit.OrphanTimeout == 0 {
		cfg.Proxy.Circuit.OrphanTimeout = 30
	}
	if cfg.Proxy.Circuit.MaxReassemblyWindow == 0 {
		cfg.Proxy.Circuit.MaxReassemblyWindow = 256
	}
	if len(cfg.Proxy.Exit.AllowedPorts) == 0 && !cfg.Proxy.Exit.AllowAllPorts {
		cfg.Proxy.Exit.AllowedPorts = []int{80, 443}
	}
	if cfg.Proxy.Exit.AuditRetentionDays == 0 {
		cfg.Proxy.Exit.AuditRetentionDays = 7
	}
	// SOCKS5 config defaults.
	if cfg.Proxy.SOCKS5.Enabled {
		if len(cfg.Proxy.SOCKS5.AllowedPorts) == 0 && !cfg.Proxy.SOCKS5.AllowAllPorts {
			cfg.Proxy.SOCKS5.AllowedPorts = []int{80, 443}
		}
		if cfg.Proxy.SOCKS5.DialTimeoutSec == 0 {
			cfg.Proxy.SOCKS5.DialTimeoutSec = 30
		}
		if cfg.Proxy.SOCKS5.IdleTimeoutSec == 0 {
			cfg.Proxy.SOCKS5.IdleTimeoutSec = 300
		}
		if cfg.Proxy.SOCKS5.MaxConnections == 0 {
			cfg.Proxy.SOCKS5.MaxConnections = 256
		}
	}
	// Relay config defaults.
	if cfg.Proxy.Relay.JitterMinMs == 0 {
		cfg.Proxy.Relay.JitterMinMs = 5
	}
	if cfg.Proxy.Relay.JitterMaxMs == 0 {
		cfg.Proxy.Relay.JitterMaxMs = 50
	}
	if cfg.Proxy.Relay.MaxCircuits == 0 {
		cfg.Proxy.Relay.MaxCircuits = 1024
	}
	if cfg.Proxy.Relay.MaxQueueDepth == 0 {
		cfg.Proxy.Relay.MaxQueueDepth = 256
	}
	// Path selection defaults.
	if cfg.Proxy.PathSelection.Mode == "" {
		cfg.Proxy.PathSelection.Mode = "manual"
	}
	if cfg.Proxy.PathSelection.Strategy == "" {
		cfg.Proxy.PathSelection.Strategy = "latency"
	}
	if cfg.Proxy.PathSelection.MaxRelaysPerPath == 0 {
		cfg.Proxy.PathSelection.MaxRelaysPerPath = 2
	}
	if cfg.Proxy.PathSelection.ProbeTimeoutSec == 0 {
		cfg.Proxy.PathSelection.ProbeTimeoutSec = 3
	}
	if cfg.Proxy.PathSelection.ProbeConcurrency == 0 {
		cfg.Proxy.PathSelection.ProbeConcurrency = 8
	}
	if cfg.Proxy.PathSelection.MaxCandidates == 0 {
		cfg.Proxy.PathSelection.MaxCandidates = 10
	}
	if cfg.Proxy.PathSelection.ProbeCacheTTLSec == 0 {
		cfg.Proxy.PathSelection.ProbeCacheTTLSec = 30
	}
	// Join config defaults.
	if cfg.Join.Enabled && cfg.Join.ListenAddr == "" {
		cfg.Join.ListenAddr = ":8443"
	}
	if cfg.Join.Enabled && cfg.Join.TokenLifetime == 0 {
		cfg.Join.TokenLifetime = 1800 // 30 minutes
	}
	// TUN config defaults.
	if cfg.Tun.Enabled && cfg.Tun.MTU == 0 {
		cfg.Tun.MTU = DefaultTunMTU
	}
	// ACL config defaults.
	if cfg.ACL.DefaultPolicy == "" {
		cfg.ACL.DefaultPolicy = ACLActionAllow
	}
	// Logging config defaults.
	if cfg.Logging.LogFile != "" {
		if cfg.Logging.LogMaxSize == 0 {
			cfg.Logging.LogMaxSize = DefaultLogMaxSize
		}
		if cfg.Logging.LogMaxBackups == 0 {
			cfg.Logging.LogMaxBackups = DefaultLogMaxBackups
		}
	}
	return cfg, nil
}

// Save writes the config to path as YAML.
func Save(path string, cfg *Config) error {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	if err := os.WriteFile(path, data, 0600); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	return nil
}

// LegacyTOTPSecret returns the deprecated totp_secret value found in
// config.yaml during Load(), or empty string if none. Used for one-time
// migration to the node-local master secret at /var/lib/meshdesk/totp/master.key.
func (a *AuthConfig) LegacyTOTPSecret() string {
	return a.legacyTOTPSecret
}

// extractLegacyTOTPSecret scans raw YAML bytes for a top-level
// auth.totp_secret field and returns its string value if present.
// This is needed because the TOTPSecret struct field was removed;
// the value is captured for migration only.
func extractLegacyTOTPSecret(data []byte) string {
	var raw map[string]map[string]any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return ""
	}
	auth, ok := raw["auth"]
	if !ok {
		return ""
	}
	secret, ok := auth["totp_secret"]
	if !ok {
		return ""
	}
	s, ok := secret.(string)
	if !ok {
		return ""
	}
	return s
}

// knownTopLevelKeys is the set of top-level YAML keys recognised by
// the Config struct. Any key not in this set is considered unknown
// and will trigger a warning during Load().
var knownTopLevelKeys = map[string]bool{
	"node":       true,
	"mesh":       true,
	"peers":      true,
	"p2p":        true,
	"monitoring": true,
	"webssh":     true,
	"auth":       true,
	"transfer":   true,
	"proxy":      true,
	"reality":    true,
	"join":       true,
	"tun":        true,
	"acl":        true,
	"logging":    true,
}

// warnUnknownTopLevelKeys unmarshals the raw YAML into a generic map
// and logs a warning for every top-level key that is not part of the
// Config struct. This helps operators identify stale sections (e.g.
// a leftover xray: block from the pre-refactor era) without causing
// a hard failure — the config still loads successfully.
func warnUnknownTopLevelKeys(data []byte) {
	var raw map[string]any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return
	}
	for key := range raw {
		if !knownTopLevelKeys[key] {
			log.Printf("[WARNING] config.yaml contains unknown top-level section '%s' — "+
				"it is ignored and can be safely removed.", key)
		}
	}
}
